"""
供应商种子数据
基于常见采购场景预设：线缆、办公用品、轴承、电子元器件、MRO 等
所有数据均为虚构示例，仅供演示使用
"""

SEED_SUPPLIERS = [
    {
        "company_name": "华中线缆科技有限公司",
        "main_products": "电力电缆, 控制电缆, 特种线缆",
        "product_categories": "线缆, 电气材料",
        "specifications": "1平方-300平方铜芯/铝芯电缆，BV/BVR/RVV/YJV系列",
        "price_range_low": 15,
        "price_range_high": 200,
        "price_unit": "元/米",
        "delivery_cycle": "3-7个工作日",
        "delivery_regions": "全国，华中地区优先",
        "quality_rating": 92,
        "credit_rating": 88,
        "service_rating": 85,
        "contact_info": "0731-****8888",
        "website": "www.hn-cable.example.com",
        "cooperation_status": "active",
        "established_year": 2008,
        "registered_capital": "5000万元",
        "employee_count": 320,
        "certifications": "ISO9001, CCC认证, 国家电网入围供应商",
        "notes": "6平方以下线缆现货充足，交货速度快"
    },
    {
        "company_name": "广州恒通线缆有限公司",
        "main_products": "电力电缆, 通信电缆, 光纤光缆",
        "product_categories": "线缆, 通信材料",
        "specifications": "铜芯/铝芯电缆各规格，含阻燃/耐火型号",
        "price_range_low": 12,
        "price_range_high": 180,
        "price_unit": "元/米",
        "delivery_cycle": "5-10个工作日",
        "delivery_regions": "华南、华中、华东",
        "quality_rating": 88,
        "credit_rating": 90,
        "service_rating": 82,
        "contact_info": "020-****6666",
        "website": "www.hengtong-cable.example.com",
        "cooperation_status": "active",
        "established_year": 2010,
        "registered_capital": "3000万元",
        "employee_count": 200,
        "certifications": "ISO9001, CCC认证",
        "notes": "大额订单价格可商议"
    },
    {
        "company_name": "长沙科力办公用品有限公司",
        "main_products": "A4纸, 打印耗材, 办公文具, 办公设备",
        "product_categories": "办公用品, 耗材",
        "specifications": "A4打印纸70g/80g，各类硒鼓墨盒，文件夹等",
        "price_range_low": 15,
        "price_range_high": 500,
        "price_unit": "元/件",
        "delivery_cycle": "1-3个工作日",
        "delivery_regions": "长沙市及周边，湖南省内",
        "quality_rating": 85,
        "credit_rating": 92,
        "service_rating": 90,
        "contact_info": "0731-****1234",
        "website": "www.kelioffice.example.com",
        "cooperation_status": "active",
        "established_year": 2015,
        "registered_capital": "500万元",
        "employee_count": 50,
        "certifications": "ISO9001",
        "notes": "办公纸品常年备货，支持次日达"
    },
    {
        "company_name": "长沙文博办公设备有限公司",
        "main_products": "A4纸, A3纸, 打印机, 复印机, 办公家具",
        "product_categories": "办公用品, 办公设备",
        "specifications": "A4 70g/80g复印纸，A3 80g复印纸，各类打印设备",
        "price_range_low": 13,
        "price_range_high": 8000,
        "price_unit": "元/件",
        "delivery_cycle": "2-5个工作日",
        "delivery_regions": "湖南省",
        "quality_rating": 82,
        "credit_rating": 85,
        "service_rating": 88,
        "contact_info": "0731-****5678",
        "website": "www.wenbo-office.example.com",
        "cooperation_status": "active",
        "established_year": 2013,
        "registered_capital": "800万元",
        "employee_count": 60,
        "certifications": "ISO14001",
        "notes": "批量采购可享9折优惠"
    },
    {
        "company_name": "上海精工轴承有限公司",
        "main_products": "深沟球轴承, 圆柱滚子轴承, 角接触轴承, 调心轴承",
        "product_categories": "轴承, 机械配件",
        "specifications": "内径10mm-500mm各型号轴承，含SKU 6205/6206/6308等",
        "price_range_low": 8,
        "price_range_high": 5000,
        "price_unit": "元/个",
        "delivery_cycle": "3-15个工作日",
        "delivery_regions": "全国",
        "quality_rating": 95,
        "credit_rating": 93,
        "service_rating": 86,
        "contact_info": "021-****9999",
        "website": "www.jg-bearing.example.com",
        "cooperation_status": "active",
        "established_year": 2000,
        "registered_capital": "1.2亿元",
        "employee_count": 800,
        "certifications": "ISO9001, ISO14001, IATF16949, SKF授权经销商",
        "notes": "6205轴承常备库存10万+，支持大批量快速交货"
    },
    {
        "company_name": "洛阳中轴传动设备有限公司",
        "main_products": "滚动轴承, 滑动轴承, 关节轴承, 轴承座",
        "product_categories": "轴承, 传动设备",
        "specifications": "国标/非标轴承，支持定制，6205/6308/UCP系列",
        "price_range_low": 6,
        "price_range_high": 3000,
        "price_unit": "元/个",
        "delivery_cycle": "5-20个工作日",
        "delivery_regions": "全国",
        "quality_rating": 90,
        "credit_rating": 86,
        "service_rating": 80,
        "contact_info": "0379-****3333",
        "website": "www.lyzc-bearing.example.com",
        "cooperation_status": "active",
        "established_year": 1995,
        "registered_capital": "8000万元",
        "employee_count": 600,
        "certifications": "ISO9001, ISO14001, GB/T19001",
        "notes": "国产品牌性价比高，非标定制能力强"
    },
    {
        "company_name": "深圳芯源电子科技有限公司",
        "main_products": "IC芯片, 电阻电容, 连接器, PCB板",
        "product_categories": "电子元器件, 半导体",
        "specifications": "各类贴片/插件电子元器件，含ST/TI/ADI代理产品线",
        "price_range_low": 0.01,
        "price_range_high": 200,
        "price_unit": "元/个",
        "delivery_cycle": "1-4周",
        "delivery_regions": "全国",
        "quality_rating": 90,
        "credit_rating": 87,
        "service_rating": 83,
        "contact_info": "0755-****7777",
        "website": "www.chip-source.example.com",
        "cooperation_status": "active",
        "established_year": 2012,
        "registered_capital": "2000万元",
        "employee_count": 150,
        "certifications": "ISO9001, ESD防护认证",
        "notes": "常用型号备货充足，紧缺物料交期需确认"
    },
    {
        "company_name": "武汉钢材贸易有限公司",
        "main_products": "冷轧板, 热轧板, 镀锌板, 不锈钢板, 型材",
        "product_categories": "钢材, 金属材料",
        "specifications": "板材厚度0.3mm-100mm，含Q235/Q345/304/316等牌号",
        "price_range_low": 4,
        "price_range_high": 50,
        "price_unit": "元/kg",
        "delivery_cycle": "5-15个工作日",
        "delivery_regions": "华中地区优先，全国可发",
        "quality_rating": 88,
        "credit_rating": 85,
        "service_rating": 80,
        "contact_info": "027-****4444",
        "website": "www.wh-steel.example.com",
        "cooperation_status": "active",
        "established_year": 2005,
        "registered_capital": "1亿元",
        "employee_count": 450,
        "certifications": "ISO9001, ISO14001, 宝钢代理商",
        "notes": "钢材价格随市场波动，报价有效期为7天"
    },
    {
        "company_name": "苏州精密机械加工有限公司",
        "main_products": "CNC加工件, 钣金件, 精密零部件, 模具",
        "product_categories": "机械加工, 定制件",
        "specifications": "±0.01mm精度，支持来图来样加工，铝/铜/不锈钢/塑料材质",
        "price_range_low": 50,
        "price_range_high": 10000,
        "price_unit": "元/件",
        "delivery_cycle": "7-30个工作日",
        "delivery_regions": "长三角优先，全国可发",
        "quality_rating": 93,
        "credit_rating": 88,
        "service_rating": 85,
        "contact_info": "0512-****2222",
        "website": "www.sz-precision.example.com",
        "cooperation_status": "active",
        "established_year": 2011,
        "registered_capital": "3000万元",
        "employee_count": 180,
        "certifications": "ISO9001, IATF16949, AS9100D(航空)",
        "notes": "高精度加工能力强，支持小批量打样"
    },
    {
        "company_name": "广州派克包装材料有限公司",
        "main_products": "纸箱, 木箱, 塑料袋, 缠绕膜, 缓冲包装",
        "product_categories": "包装材料, 耗材",
        "specifications": "各种尺寸纸箱/木箱定做，PE袋/气泡袋/EPE珍珠棉",
        "price_range_low": 0.5,
        "price_range_high": 200,
        "price_unit": "元/个",
        "delivery_cycle": "2-7个工作日",
        "delivery_regions": "广东省及周边",
        "quality_rating": 80,
        "credit_rating": 84,
        "service_rating": 82,
        "contact_info": "020-****5555",
        "website": "www.pack-best.example.com",
        "cooperation_status": "active",
        "established_year": 2016,
        "registered_capital": "500万元",
        "employee_count": 40,
        "certifications": "ISO9001, 出口包装认证",
        "notes": "定制包装起订量100个起"
    },
    {
        "company_name": "杭州艾科信息技术有限公司",
        "main_products": "企业软件, ERP系统, OA系统, 采购管理平台",
        "product_categories": "软件服务, IT系统",
        "specifications": "SaaS/私有部署企业管理系统，含采购/库存/财务模块",
        "price_range_low": 5000,
        "price_range_high": 500000,
        "price_unit": "元/年",
        "delivery_cycle": "15-60个工作日",
        "delivery_regions": "全国",
        "quality_rating": 87,
        "credit_rating": 90,
        "service_rating": 92,
        "contact_info": "0571-****1111",
        "website": "www.aike-it.example.com",
        "cooperation_status": "active",
        "established_year": 2014,
        "registered_capital": "2000万元",
        "employee_count": 120,
        "certifications": "ISO27001, CMMI3, 国家高新技术企业",
        "notes": "采购管理模块支持定制开发"
    },
    {
        "company_name": "北京东方化工原料有限公司",
        "main_products": "工业溶剂, 催化剂, 表面处理剂, 清洗剂",
        "product_categories": "化工原料, 工业化学品",
        "specifications": "各类工业级/试剂级化工原料，含危险化学品经营许可",
        "price_range_low": 3,
        "price_range_high": 500,
        "price_unit": "元/kg",
        "delivery_cycle": "3-10个工作日",
        "delivery_regions": "华北、华东地区",
        "quality_rating": 86,
        "credit_rating": 82,
        "service_rating": 78,
        "contact_info": "010-****8888",
        "website": "www.bj-chem.example.com",
        "cooperation_status": "active",
        "established_year": 2003,
        "registered_capital": "5000万元",
        "employee_count": 200,
        "certifications": "ISO9001, 危化品经营许可证, ISO14001",
        "notes": "危化品运输需提前确认资质"
    },
]
